name: riverpod_2_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hooks_riverpod: ^2.3.4
  injectable: ^2.1.1
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.5

flutter:
  uses-material-design: true
